version: '3.8'

services:
  php:
    image: php:8.2-cli
    container_name: php-scraper
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - chrome
    environment:
      - TZ=Asia/Tokyo
    networks:
      - scraping-network

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome-browser
    ports:
      - "4444:4444"
    networks:
      - scraping-network

networks:
  scraping-network:
    driver: bridge
